// Auto-generated from Department of Shipping Approved Agents List
// Source: Agents List.pdf
import { ManningAgent } from '../types';

export const APPROVED_AGENTS: ManningAgent[] = [
  {
    id: '1',
    licenseNumber: 'MLA-002',
    name: 'Unicorn Shipping Services Limited',
    address: 'Finlay House (4th Floor), 11 Agrabad, C/A, Chattogram',
    phone: '+88 031 712483 Fax : +88 031 713983',
    email: 'unicornchittagong@unicornship.com',
    website: 'www.unicornship.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '2',
    licenseNumber: 'MLA-003',
    name: 'Reliance Shipping Services',
    address: 'Nur Chamber, (3rd Floor) 34,, Agrabad Commercial Area,, Chattogram-4100., Mohammed, Abul Khair, 29-05-, 2026',
    phone: 'N/A',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '3',
    licenseNumber: 'MLA-004',
    name: 'Universal Shipping Services',
    address: 'Room No-13, (6th Floor) 3/D, Kawran Bazar Road, Kabyaks, super market, Dhaka.',
    phone: '01715331535, Tel: 8809611656255',
    email: 'kak.uss.bd@gmail.com',
    website: 'www.universalbd.org',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '4',
    licenseNumber: 'MLA-008',
    name: 'Haque & Sons Ltd.',
    address: 'Rummana Haque Tower 1267/A,, Goshail Danga, Agrabad, Chattogram.',
    phone: '031-716214-6, 710266, Fax : 031-710530, 710288',
    email: 'haqsinsctg@haqsons.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '5',
    licenseNumber: 'MLA-009',
    name: 'JF (Bangladesh) Limited',
    address: 'Finlay House, 11- Agrabad, C/A, Chattogram., Ahamed, Quamrul Islam, Chowdhury, 28 June, 2026',
    phone: '031-716321-5Fax : 031-710006, 710207',
    email: 'jfbdltd@bdmail.net',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '6',
    licenseNumber: 'MLA-011',
    name: 'Marine (Agency) Services Ltd.',
    address: 'House No- 1 (4th Floor)Lane-5, Block -1, Road-1, Halishar Housing estate P.O- Rampur, Chattogram.',
    phone: '+88 031 727577, Phone: 017 30047450,',
    email: 'operation@masbd.info',
    website: 'www.masgroupbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '7',
    licenseNumber: 'MLA-013',
    name: 'Sigma Shipping Lines',
    address: 'House # 5C, Zakir Hossain Road,, Pahartali, Khulshi, Chattogram.',
    phone: '031-711317 Fax : 031-2520536',
    email: 'sigmaship@colbd.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '8',
    licenseNumber: 'MLA-014',
    name: 'Printik Marine Services Limited',
    address: 'Akhtaruzzaman Centre (7th floor),, 21/22 Agrabad Commercial Area,, Chittagong-4100',
    phone: '+8802333310525, Phone: 01730004257',
    email: 'info@prantik.net',
    website: 'www.prantik.net',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '9',
    licenseNumber: 'MLA-022',
    name: 'Bay Shipping Services',
    address: 'The Heaven(5th Floor), 1335/A, Nikunja R/A,, South Khulshi, Chattogram-4202.',
    phone: '88-031-2513879, Phone: 01833363448,',
    email: 'crew@bayshipping.net',
    website: 'www.bayshipping.net',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '10',
    licenseNumber: 'MLA-023',
    name: 'International Marine Services',
    address: 'House No. 317, Road No. 14 CDA, Agrabad, Chattogram.',
    phone: '01715-024167,01718227411 Fax : 031-816895,',
    email: 'iimt@techno-bd.net',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '11',
    licenseNumber: 'MLA-024',
    name: 'PIL (Bangladesh) Ltd.',
    address: 'IIUC Tower (5th Floor),Plot # 09,, Sk. Mujib Road, Agrabad C/A Chattogram.',
    phone: '031-713301-6, 727791, Fax : 031-710301',
    email: 'pildhk@citechco.net',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '12',
    licenseNumber: 'MLA-025',
    name: 'KSF Shipping Services',
    address: 'House # 131(3rd floor), Road # 17 CDA R/A,, Agrabad, Chattogram.',
    phone: '031-711023, 711737 Fax : 031-710756',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '13',
    licenseNumber: 'MLA-026',
    name: 'NYK Line (Bangladesh) Ltd.',
    address: 'Land View Commercial Center(14th Floor) 28,, Gulshan North C/a,Culshan Circle-2, Dhaka-1212,',
    phone: '+88 02 8852703, Fax: +88 02 8852705',
    email: 'bgd-info@bd.nykline.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '14',
    licenseNumber: 'MLA-028',
    name: 'Bluestar Services Limited.',
    address: 'Bluestar House, House #12, Road#09, Block-J,, Baridhara (Progati Sarani Road) Dhaka-1212',
    phone: '+880-1819217093, Tel: +88-02-58814973',
    email: 'info1@bluestarbd.com',
    website: 'www.bluestarbd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '15',
    licenseNumber: 'MLA-030',
    name: 'Ever Cheer Marine Services',
    address: 'Suit No. 703(6th Floor), South Land Centre 05,, Agrabad C/A. Chattogram-4100',
    phone: '+88-02333319485, +88-02333319487',
    email: 'info@evercheerbd.com',
    website: 'www.evercheerbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '16',
    licenseNumber: 'MLA-035',
    name: 'Shoreline ServicesLimited',
    address: 'Delower Bhaban(4th Floor),, 104 Agrabad C/A, Chattogram-4100',
    phone: '+88-02-333322814-15, Fax : +88-02-3333 11268',
    email: 'info@shorelinbd.com',
    website: 'www.shorelinebd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '17',
    licenseNumber: 'MLA-036',
    name: 'S.K. Engineering',
    address: 'House no.1159/1, Shahapur, Jamalpur',
    phone: '+88 01715032862',
    email: 'info@slengineering.info',
    website: undefined,
    status: 'Active',
  },
  {
    id: '18',
    licenseNumber: 'MLA-040',
    name: 'Asia Marine Agency',
    address: 'Al-Razi Complex (7th Floor) Suit # D-701,, 166-167, Shaheed Syed Nazrul Islam Sarani, Purana Paltan,, Dhaka-1000',
    phone: '+880-2-9556768, 9556769. Fax- +880-2-9556770',
    email: 'infoama@asiatelnet.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '19',
    licenseNumber: 'MLA-044',
    name: 'B.N.F. Shipping Services',
    address: 'Skay Lark point, Suit No-G2(6th floor),, 24/A Bijoy nager, Dhaka',
    phone: '9342987, Fax: 9350127',
    email: 'bnfshipping@gmail.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '20',
    licenseNumber: 'MLA-047',
    name: 'Aquamarine Bangladesh Ltd.',
    address: 'Comfort Niketon, House-77, Flat-2B, Road-4, Block-B,, Niketan, Gulshan-1, Dhaka-1212.',
    phone: '+880-2-9840591-93, Phone. 0178 6434 642.',
    email: 'crewing@aquamarinebd.com',
    website: 'www.aquamarinebd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '21',
    licenseNumber: 'MLA-051',
    name: 'Mercantile Shipping Lines Ltd.',
    address: 'Fresh Villa, House No-15, Road No-34 Gulshan-1, Dhaka-1212.',
    phone: '+88 09666777055, +88-02  9889490, Fax: +88 02  9884896',
    email: 'info@mgi.org',
    website: 'www.mgi.org',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '22',
    licenseNumber: 'MLA-060',
    name: 'Brave Royal Ship Management (BD) Limited',
    address: 'Kabir Manzil (4th Floor) Sheikh Mojib Road,, Agrabad C/A. Chattogram-4100',
    phone: 'o-031-2510457, 2514780, Fax-031-2510458',
    email: 'info@vmlbd.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '23',
    licenseNumber: 'MLA-061',
    name: 'Vanguard Maritime Limited',
    address: 'Afrif Chamber, 98-Agrabad C/A, Chattogram',
    phone: '+88 031 2510457 Fax-+88 031 2510458',
    email: 'E-mail-info@vmlbd.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '24',
    licenseNumber: 'MLA-063',
    name: 'Sea Gold Shipping Services',
    address: 'House No.-13(Ground Floor),, Road No.-3, Lane No.-5, Block-K, Halishahar, Chattogram',
    phone: 'No.: +880-31-717132, Phone No. +880-1827566485',
    email: 'latif@seagoldshippingbd.com',
    website: 'www.seagoldshippingbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '25',
    licenseNumber: 'MLA-065',
    name: 'East Coast Shipping Lines Ltd',
    address: 'East Coast House,  138/A  CDA R/A, Road No. 01, Agrabad,, Chittagong.',
    phone: 'No. : +880-31-710010, +880-31-713266, Phone No.:+88-',
    email: 'Eastcoast@ecg.com.bd',
    website: 'www.ecg.com.bd',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '26',
    licenseNumber: 'MLA-067',
    name: 'Mariners Bangladesh Services Ltd.',
    address: 'Permanent Address: Vill-Bishnupur, Post-Mayura, Ps-Nangolkot,, Dist-Comilla., Present Address: A R Tower, (Ground Floor), Rahamanbag,, Aggrabad Access road, Chattogram.',
    phone: '+8801717791475',
    email: 'marinersbdservices@gmail.com',
    website: 'www.basmshipbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '27',
    licenseNumber: 'MLA-070',
    name: 'Sea King Marine Services Limited',
    address: '10th Floor, Aktharuzzaman Center 21/22 Agrabad C/A,, Chattogram',
    phone: '+88 031-717253 Tel:+88-01844177255',
    email: 'operation@skmsbd.com',
    website: 'www.skmsbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '28',
    licenseNumber: 'MLA-071',
    name: 'Unicorn Marine Ltd.',
    address: 'Sadharan Bima Sadan (2nd floor), 102, Agrabad C/A, Chittagong.',
    phone: '031-727465 Fax: 031-713983',
    email: 'marine@unicornship.com',
    website: 'www.unicornship.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '29',
    licenseNumber: 'MLA-073',
    name: 'Naaf Marine Services',
    address: 'Portland Sattar Tower (5th Floor) 1776 Strand Road,, East of Barik Building, Agrabad, Chattogram',
    phone: '031-717308-09, 2518660, Fax: 031-716101',
    email: 'info@naafmarine.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '30',
    licenseNumber: 'MLA-075',
    name: 'GSP Marine Services',
    address: 'Meem Tower, House: 33 (2nd Floor), Road: 03, O.R. Nizam, Road,, East Nasirabad, Chattogram.',
    phone: '+880 31 652337, Phone: +880 1820547433',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '31',
    licenseNumber: 'MLA-076',
    name: 'Fazila Marine',
    address: 'House No.39, Road-07, Sector-12, Uttara, Dhaka-1230',
    phone: '+88 02 55085439, Fax: +88 02 55085439',
    email: 'fazilamarine@yahoo.com',
    website: 'www.fazilamarine.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '32',
    licenseNumber: 'MLA-077',
    name: 'Shah Shipping Recruiting Agency',
    address: 'Vill: Bokchar, Union: Jamirta, P.S: Singair, Dist:, Manikganj, Present: House-36, Road-3, Block A, PC Culture Housing,, Ring Road, Shyamoli, Mahammadpur, Dhaka-1207',
    phone: '01730494427, 01799884008',
    email: 'crew@shah-shipping.com',
    website: 'www.ssrabd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '33',
    licenseNumber: 'MLA-080',
    name: 'A. Z. SHIPPING SERVICES',
    address: 'Silver Castle, Bepari Para, Mosque-CDA by Lane, Agrabad,, Chattogram',
    phone: '031-2524486, 031-2528581, 031-2520086(Res)',
    email: 'gaffarazshipping@gmail.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '34',
    licenseNumber: 'MLA-081',
    name: 'Seafarers Placement Services',
    address: 'House-X61/1, Road-3, Block-A, Chandgoa R/A, Chittagong., & House-1, Road-1, Lane-5, Block-L, Halishahar Housing, Estate, Chattogram.',
    phone: '+88 031 2516314, Fax: +88 031 723161',
    email: 'seafarersplacementservices@gmail.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '35',
    licenseNumber: 'MLA-082',
    name: 'JAR World Marine (Pvt) Limited',
    address: 'Anayat Ali Member`s House, Middle Halishahar Monsipara,, P.O-Ananda Bazar, P.S. Bandar, Chittagong., & Milinium Plaza (4th Floor), 2905, Agrabad Ex., Road, Chattogram.',
    phone: '+88 031 2530011, Fax: +88 031 2514088',
    email: 'shipmanning@jarship.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '36',
    licenseNumber: 'MLA-083',
    name: 'Atlantic Shipping Services',
    address: 'House # 02, Road # 11, Block # F, Banani, Dhaka-1213',
    phone: 'No: +880 2 9870536,9870885-6, Fax No: +880 2 9870536',
    email: 'crew@atlssmg.com',
    website: 'www.atlssmg.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '37',
    licenseNumber: 'MLA-085',
    name: 'Golden Carrier Ship Management',
    address: 'Tulatoli Road, Faujdarhat, Chittagong., &  House # 10 (3rd Floor), Road # 31, Sector # 7,, Uttara, Dhaka-1230., Maruf Md., Jahirul Islam, 20-12-, 2025',
    phone: '880-31-2781238-9Fax: 880-31-2781240',
    email: 'maruf_engr77@yahoo.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka", "Chittagong"],
  },
  {
    id: '38',
    licenseNumber: 'MLA-088',
    name: 'S.S. Marine Service',
    address: 'House # 61, Road # 1, Bashundhara R/A, Dhaka-1230',
    phone: '880-2-8401774, Fax: 880-2-8401774, Phoneil- +88',
    email: 'ssmarineservicee@gmail.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '39',
    licenseNumber: 'MLA-089',
    name: 'ASP Crew Management Limited',
    address: 'House: 467(1 Floor), Road :31, Mohakhali DOHS, Dhaka-1206.',
    phone: '+88 02 9884312-7, +88 01711475995 Fax: +88 02',
    email: 'mzaber@aspships.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '40',
    licenseNumber: 'MLA-092',
    name: 'Expert Associate Limited',
    address: 'House No: 5, Road # 3, Sector # 7, Uttara, Dhaka-1236',
    phone: '880-27553573,Fax: 880 27553573 Cell: 01790356530',
    email: 'info@expertassociate.biz',
    website: 'www.expertassociate.biz',
    status: 'Suspended',
    cities: ["Dhaka"],
  },
  {
    id: '41',
    licenseNumber: 'MLA-094',
    name: 'R.B.M Maritime Limited',
    address: '506, Omar Shajahan Tower (3rd Floor), Shah Kabir Mazar Road,, Azampur Railgate, Uttara, Dhaka-1230.',
    phone: 'No.: +88-031-2515361,2511529',
    email: 'info@rbmgroupbd.net.net',
    website: 'www.rbmgroupbd.net',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '42',
    licenseNumber: 'MLA-096',
    name: 'Ayar Shipping Services',
    address: 'Kh Tower, (5th Floor), Plot # 10, Lane # 05, Road # 01,, Block # L, Arabad Access Road, Halishahar,Boropool,, Chattogram',
    phone: '88-031-2517173, Fax: 88-031-2517173',
    email: 'info@ayarship.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '43',
    licenseNumber: 'MLA-097',
    name: 'South Asia Ship Crewing Agent',
    address: 'Metro Plaza (4th Floor), 79/A- Sadarghat Road,, Room No- 501, Opposite Kali Bari, Chittagong.',
    phone: '88-031-2853773, Fax: 88-031-2853774',
    email: 'south.asia16@gmail.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '44',
    licenseNumber: 'MLA-098',
    name: 'Marine Hive Ltd.',
    address: '25, Gorib-e-Newaz Avenue, Flat-A2 Sector#11,, Uttara Model Town Dhaka-1230',
    phone: '+88 02 7913662',
    email: 'crewing@marinehive.com',
    website: 'www.marinehive.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '45',
    licenseNumber: 'MLA-099',
    name: 'Dolphin Maritime Services Limited',
    address: 'Nishorgo (Ground Floor), House no-1, Road no-A/1,, Karnafuly R/A, Halishahar, Chittagong, Bangladesh., S.M.A.Hannan 24-03-, 2026',
    phone: 'N/A',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '46',
    licenseNumber: 'MLA-101',
    name: 'Zebra Shipping Limited',
    address: '15, Strand Road, Majhirghat, Chattogram-4000',
    phone: '088031-618940,618975, Fax:088031-610067',
    email: 'zebrashippingbd@gmail.com',
    website: undefined,
    status: 'Expired',
    cities: ["Chittagong"],
  },
  {
    id: '47',
    licenseNumber: 'MLA-102',
    name: 'Sailor Bangladeah Limited',
    address: 'Suite no-1A,(1st floor), Entaj Ali Pradaise, 43/1/7,, Atish Diponkar Road, Sabuj Kanon, Basabo, Dhaka-1000, Md. Zafor, Sadik, 13-03-, 2027',
    phone: 'N/A',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '48',
    licenseNumber: 'MLA-103',
    name: 'Shobuj Bangla Shipping Service Limited',
    address: 'House No : 13, Road No : 02, Lane No : 03 Block-K,, Halishahar, Chattogram-4216',
    phone: 'No : +88-031-2527891, Phoneil. No. +880-1869579796',
    email: 'crew@shbss.com.bd',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '49',
    licenseNumber: 'MLA-104',
    name: 'Marine Fleet Shipping Limited',
    address: '74(1st Floor), Road No.-27, C.D.A R/A, Agrabad, Chittagong 4100',
    phone: '880-31-714741, 2528631, Fax: 880-31-710025',
    email: 'marinefleetbd@gmail.com',
    website: 'www.marinefleetbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '50',
    licenseNumber: 'MLA-105',
    name: 'Global Ocean Shipping Services Ltd.',
    address: 'Flat No. B/2, House No.13, Road No.11, Sector No. 11,, Uttara Model Town, Dhaka-1230',
    phone: 'Bangladesh. Phone: 01781666777, 01672698555,',
    email: 'operations@globaloceanssl.com',
    website: 'www.globalocenssl.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '51',
    licenseNumber: 'MLA-106',
    name: 'Unipole Shipping Services',
    address: 'Present Address: Chairman Center(2nd Floor),, House No-1, Road No.-2, Lane No-3, Gate No-9,, Block-K Halishahar H/E, P.C Road, Chittagong',
    phone: '88-031-715614, Fax: 88-031-715614',
    email: 'crewing@unipoleshipping.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '52',
    licenseNumber: 'MLA-107',
    name: 'Good Luck Maritime Ltd.',
    address: '201, K.Y Tower, Gulbag, Agrabad Access Road,, Agarbad, Chattogram., Mohabbat Ali, Siddique Apon, Chowdhury, 15-04-, 2026',
    phone: '+88 02333318388, Phone: +88 01756022448,',
    email: 'info@goodluckmaritime.com',
    website: 'www.goodluckmaritime.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '53',
    licenseNumber: 'MLA-108',
    name: 'Compass  Shipping Service Ltd.',
    address: 'Sultan Hajer Bari, Kusumpura, Kalarpool, Patiya,Chattogram., Md. Atikur, Rahman, Managing, Director, 09-12-, 2026',
    phone: 'N/A',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '54',
    licenseNumber: 'MLA-109',
    name: 'Elite Maritime Ltd.',
    address: '1557, Hazipara Singapore Market, Romm: 612, 5th floor,, Agrabad  Access Road, Chattogram., Habibur, Rahman, Chairman, 11-12-, 2022',
    phone: 'N/A',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '55',
    licenseNumber: 'MLA-110',
    name: 'NSP Shipping Services Ltd.',
    address: 'Permanent Address: 349, North Shahjahan Pur,, P.O: Shantinagor, Thana: Shahjahan Pur, District: Dhaka.',
    phone: 'No.: +88-০2-48322127, 48321925-6, Phone:+880-1777543980',
    email: 'niazmud4@yahoo.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '56',
    licenseNumber: 'MLA-111',
    name: 'Sea Express Ltd.',
    address: 'Shahidullah Bahabon, H-01/A (4th Floor), Road-02,, Lame-03, Block-K, Halishahar H/E, Halishahar, Chittagong',
    phone: '+88-0161 0383 868',
    email: 'info@seaexpressltd.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '57',
    licenseNumber: 'MLA-112',
    name: 'MSM Marine & Shipping Services',
    address: 'R.I. Tower (Level 6), 23/A M.M Ali Road, Mehedibag,, Chattogram-4000',
    phone: 'No.: +88-031-2859929, Phoneil +880-1844470870',
    email: 'info@msmshippingservices.com',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '58',
    licenseNumber: 'MLA-113',
    name: 'Falcon Marine Services Ltd',
    address: 'Plot #21 (Ground Floor), Road #9/A, Nikunja R/A-1,, Khilkhet, Dhaka',
    phone: '+880-1748 196658, 01712 190562',
    email: 'ashraf@fmslbd.com',
    website: 'www.bsmssl.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '59',
    licenseNumber: 'MLA-114',
    name: 'MariAid Limited',
    address: 'Rahima Concord, House No.-18(4th Floor),, Road No,-1, Sector No.-5, Uttara Model Town, Dhaka-1230.',
    phone: 'No.: +88-02-48956769, 01712 201060',
    email: 'motin@mariaid.com',
    website: 'www.mariaid.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '60',
    licenseNumber: 'MLA-116',
    name: 'Karnaphuli Maritime Limited',
    address: 'HR Bhaban, 26/1 Kakrail, Dhaka- 1000',
    phone: 'No. +880-2- 58310167-73,Fax  880 -2- 48314948,',
    email: 'info@karnaphuli.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '61',
    licenseNumber: 'MLA-117',
    name: 'Gemini Maritime Agency Bangladesh',
    address: 'Flat 6B, (7th Floor), House no: 245/1, & 247 South Paikpara,, Mirpur, Dhaka-1216',
    phone: 'No. +880-1810020098',
    email: 'info@geminimaritimebd.com',
    website: 'www.geminimaritimebd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '62',
    licenseNumber: 'MLA-118',
    name: 'Forazi Shipping Limited',
    address: 'Finlay House (4th Floor),, 11 Agrabad C/A, Chattogram-4100.',
    phone: 'No. +880-1629 722 247',
    email: 'info@fsltd.net',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '63',
    licenseNumber: 'MLA-119',
    name: 'Green Ship Services',
    address: 'Castle Queen, 4/B, House No.- 8, Road No.- 2, Lane No.-2,, Block-G, Halishahar, Chattogram, Permanent address- Shluk Mura, Bhubanghar,, Post code: 3500, Kotrwali Model, Cumilla',
    phone: 'No. +880-2333311618, Phoneil +880 1915 955 942',
    email: 'operation@greenshippingservice.com',
    website: 'www.greenshippingservice.comt',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '64',
    licenseNumber: 'MLA-120',
    name: 'Royal Marine Management',
    address: 'Hashem Tower (1st Floor),, M.A.Aziz Road, South Halishahar, Chittagong-4100',
    phone: '018163-62109',
    email: 'royalmarine1975@yahoo.com',
    website: 'www.royalmarinebd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '65',
    licenseNumber: 'MLA-121',
    name: 'K-line Maritime CO. Limited',
    address: 'Akhi Palace, House: 01, Road: 01, Lane: 02, Block: G,, Boropool, Halishahar, Chattogra.',
    phone: '+880-01923-459015 TNT: +880-02333324113',
    email: 'klinemaritime@yahoo.com',
    website: 'www.k-linemaritime.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '66',
    licenseNumber: 'MLA-122',
    name: 'Ocean Hub Ltd',
    address: 'F-10, House: 17, Sector: 13, Uttara, Dhaka',
    phone: '02-48956150, Phone: 01880282126',
    email: 'crewing@oceanhubbd.com',
    website: 'www.oceanhubbd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '67',
    licenseNumber: 'MLA-123',
    name: 'CK Maritime Ltd.',
    address: 'Permanent Address: 30/A, Noya Palton, Sattar Tower (10th Floor), V.I.P Road, Dhaka-1000, & Present Address: House-836, Apt-8A, Road-12,, Avenue-3, Mirpur DOHS, Dhaka-1216',
    phone: '+880 1710850109',
    email: 'info@ckmaritimebd.com',
    website: 'www.ckmaritimebd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '68',
    licenseNumber: 'MLA-124',
    name: 'Bluewave Shipping Pvt. Ltd.',
    address: 'Permanent Address: House-50, Garib-E-Newaz Avenue Road,, Section-13, Uttara-1230, Dhaka., Present Address: 522 SK, Mujib Road, 3rd Floor, Choumohoni,, Agrabad, Chattogram-4100.',
    phone: '01894800459',
    email: 'crewing@bluewaveshippingservices.com',
    website: 'www.bluewaveshippingservices.com',
    status: 'Active',
    cities: ["Dhaka", "Chittagong"],
  },
  {
    id: '69',
    licenseNumber: 'MLA-125',
    name: 'Aristocarat Merchant Marine Services Limited.',
    address: 'Permanent Address: Bismillah Tower, 580/7, North Kafrul, Dhaka, Cantonment, Dhaka-1206, Present Address: 501/5, East Kazipara, Kafrul, Mirpur,, Dhaka, Bangladesh.',
    phone: '01521516198',
    email: 'Crewing@aristocratbd.com',
    website: 'www.aristocratbd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '70',
    licenseNumber: 'MLA-126',
    name: 'QNS Intermodal Logistic Limited.',
    address: 'Permanent Address: Aziz Court (22th Floor), 88-89,, Agrabad C/A, Chattogram., Present Address: Aziz Court (22th Floor), 88-89,, Agrabad C/A, Chattogram.',
    phone: '01897-657619',
    email: 'intermodal@qnscorp.com',
    website: 'www.qnsglobal.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '71',
    licenseNumber: 'MLA-127',
    name: 'Vigilant Shipping Ltd.',
    address: 'Permanent Address: Flat No-5B, House No: 10,, Road: Main Road, Block: K, South Banasree, Khilgaon, Dhaka 1219, Present Address: Flat No-5B, House No: 10, Road: Main Road,, Block: K, South Banasree, Khilgaon, Dhaka-1219',
    phone: '+8801325061572, Tel: +880258054529',
    email: 'info@vigilantshippingbd.com',
    website: 'www.vigilantshippingbd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '72',
    licenseNumber: 'MLA-128',
    name: 'Capella Shipping Services.',
    address: 'Permanent Address: 10/A, Road-06, Plot-1, Pallabi,, Mirpur, Dhaka-1216., Present Address: 10/A, Road-06, Plot-1, Pallabi,, Mirpur, Dhaka-1216.',
    phone: '+880258054529, Phone: +8801684206292',
    email: 'info@capellashippingservices.com',
    website: 'www.capellashippingservices.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '73',
    licenseNumber: 'MLA-130',
    name: 'Premier Marine Services.',
    address: 'Permanent Address: House: 17, (Level-02, Flat-F/4),, Road: 14, Sector-13, Uttara Model Town, Dhaka-1230., Present Address: 17, (Level-02, Flat-F/4), Road: 14,, Sector-13, Uttara Model Town, Dhaka-1230.',
    phone: '+8802-55087530, Phone: +8801790191021,',
    email: 'info@prmsbd.com',
    website: 'www.prmsbd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '74',
    licenseNumber: 'MLA-131',
    name: 'AHP Marine Services',
    address: 'Present Address: Road No: 17, House No: 111/B,, 2nd Floor, Agrabad, CDA Residential Area, Port, Chittagong., Permanent Address: Mo: Abul Hossain House,, North Patenga Dhum Para, Po: Middle Patenga,, Upazila: Patenga, District: Chittagong',
    phone: '+8801919672368',
    email: 'N/A',
    website: undefined,
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '75',
    licenseNumber: 'MLA-132',
    name: 'NTN Oceanic Pledge Ltd.',
    address: 'Permanent Address: Tonmoy Nir, Madhumallar Dangi,, Khulna Road Mor, Satkhira., Present Address: “Isabella Tower” Level-9A (8th Floor),, Plot No:1&3, Road-7, Block-G, Boropool,, Halishahar Housing Estate Chattogram.',
    phone: '+8802333313216, +8801719031737',
    email: 'info@ntnopltd.com.bd',
    website: 'www.ntnopltd.com.bd',
    status: 'Active',
    cities: ["Chittagong", "Khulna"],
  },
  {
    id: '76',
    licenseNumber: 'MLA-133',
    name: 'Divine Marine Services Bangladesh Ltd.',
    address: 'B-7 (7th Floor), House-75, Road 14, Sector-13, Uttara, Dhaka.',
    phone: '+880241360049, Mobile: +8801974958689',
    email: 'info@dmsbl.com.bd',
    website: 'www.dmsbl.com.bd',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '77',
    licenseNumber: 'MLA-134',
    name: 'Glory-Wind Shipping Services Pvt. Ltd.',
    address: 'House No-07., Road No-07, Block-G, Boropool,, Halishahar H/E, Chattagram.',
    phone: '+880 1610-959446',
    email: 'glorywindltd@gmail.com',
    website: 'www.glorywindpvt.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '78',
    licenseNumber: 'MLA-135',
    name: 'Efficient Global Limited',
    address: 'House No-101, (3rd Floor left), Road No-06,, Railway Housing Society, Akbarsha, Chattogram.',
    phone: '02333379452, Mobile: 01973215984',
    email: 'info@efficientglobalbd.com',
    website: 'www.efficientglobalbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '79',
    licenseNumber: 'MLA-136',
    name: 'Pride Shipping Lines',
    address: 'Akhtaruzzaman Centre, (11th Floor) 21/22, Agrabad C/A, Chattogram.',
    phone: '+8801706171343',
    email: 'pride@colbd.com',
    website: 'www.prideshippingbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '80',
    licenseNumber: 'MLA-137',
    name: 'Tiger Shipping Services',
    address: 'Permanent Address: Vill-Batikamari, P.O: Batikamari, P.S:, Sarisabari, Dist: Jamalpur., Present Address: TGB, MDC BM Port View, Titas Tower (Ground, Floor),, Chatopole, Road, Boropole, Halishahar, Chattagram.',
    phone: '+880 1715365213',
    email: 'belalh63@gmail.com',
    website: 'www.tigershippingbd.com',
    status: 'Active',
    cities: ["Chittagong"],
  },
  {
    id: '81',
    licenseNumber: 'MLA-138',
    name: 'Eureka Ship Management',
    address: '23, Captain Shahid Monsur Ali, Road,, Syed Md., Sajid-Ul-Enam, (Managing, Partner), 12-05-, 2027, (3rd Floor), Flat:3/A, Ramana, Dhaka-1217',
    phone: '+880 1911666828',
    email: 'sajid.marine@gmail.com',
    website: 'www.esmbd.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '82',
    licenseNumber: 'MLA-139',
    name: 'Imperial Shipping Services',
    address: 'Permanent Address: 136/6, Pakuria Road, Beside Uttara Sector 14, Ps-Turag, Dist-Dhaka., Present Address: 10/6, Baigartek, Dhaka Cantonment, Pallabi,, Dhaka.',
    phone: '+8801841974774',
    email: 'info@impshipping.com',
    website: 'www.impshipping.com',
    status: 'Active',
    cities: ["Dhaka"],
  },
  {
    id: '83',
    licenseNumber: 'MLA-140',
    name: 'Sunrise International Shipping Company',
    address: 'Permanent Address: Vill:West khada, P.O: Rayanda, P.S:, Sarankhola, Dist: Bagerhat, Present Address: Flat: 6D, Mamtaj Villa: 10, Plot: 4, Block: F,, Road: S-1, Eastern Housing, Pallabi 2nd Phase, Rupnagar,, Mirpur, Dhaka-1216',
    phone: '+8801761-950568',
    email: 'crewing@sunriseintshipping.com',
    website: undefined,
    status: 'Active',
    cities: ["Dhaka"],
  },
];